/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spksaw;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author Acer
 */
public class Beranda extends javax.swing.JInternalFrame {

 
   
   
    Connection con;
    Statement stt;
    
    int a,b,c;
    /**
     * Creates new form Beranda1
     */
    public Beranda() {
        initComponents();
        
      
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        l_nm1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        l_nm2 = new javax.swing.JLabel();

        setFrameIcon(null);
        getContentPane().setLayout(null);

        jPanel17.setBackground(new java.awt.Color(153, 0, 0));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(906, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        getContentPane().add(jPanel17);
        jPanel17.setBounds(0, 0, 1010, 50);

        l_nm1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        l_nm1.setForeground(new java.awt.Color(153, 0, 0));
        l_nm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_nm1.setText("Penilaian Karyawan Metode SAW");
        getContentPane().add(l_nm1);
        l_nm1.setBounds(220, 220, 670, 60);

        lbl1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(153, 0, 0));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl1.setText("By : Irfan Setiawa");
        getContentPane().add(lbl1);
        lbl1.setBounds(650, 290, 230, 29);

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));

        lbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(51, 51, 51));
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl.setText("Youtube Channel => Irfan Setiawan");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(662, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel16);
        jPanel16.setBounds(0, 410, 1020, 40);

        l_nm2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        l_nm2.setForeground(new java.awt.Color(153, 0, 0));
        l_nm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_nm2.setText("S e l a m a t   d a t a n g   d i  P r o g r a m");
        getContentPane().add(l_nm2);
        l_nm2.setBounds(30, 160, 920, 60);

        setBounds(0, 0, 1022, 476);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JLabel l_nm1;
    private javax.swing.JLabel l_nm2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    // End of variables declaration//GEN-END:variables
}
